all:
	$(MAKE) -C adslate
	$(MAKE) -C auto_det
	$(MAKE) -C tp_init
        	

install: 
	$(MAKE) -C adslate install
	$(MAKE) -C auto_det install
	$(MAKE) -C tp_init install
        	

clean:
	$(MAKE) -C adslate clean
	$(MAKE) -C auto_det clean
	$(MAKE) -C tp_init clean
